#!/usr/bin/env python3
"""Embed kiosk icons into code.js for offline Figma plugin use.

Prefers assets/icons/*.png (run split_kiosk_icons.py first) for per-icon FILL
instead of sheet CROP. Falls back to assets/asak-kiosk-icons-4x4.png.
"""
from __future__ import annotations

import argparse
import base64
import re
import sys
from pathlib import Path

PLUGIN_DIR = Path(__file__).resolve().parent
if str(PLUGIN_DIR) not in sys.path:
    sys.path.insert(0, str(PLUGIN_DIR))

from split_kiosk_icons import DEFAULT_OUT as ICONS_DIR, ICON_NAMES, SPEC_NAME_BY_FILE

CODE_JS = PLUGIN_DIR / "code.js"
IMAGE_PATH = PLUGIN_DIR / "assets" / "asak-kiosk-icons-4x4.png"

SHEET_MARKER_START = "// KIOSK_ICONS_START"
SHEET_MARKER_END = "// KIOSK_ICONS_END"
INDIV_MARKER_START = "// KIOSK_ICONS_INDIVIDUAL_START"
INDIV_MARKER_END = "// KIOSK_ICONS_INDIVIDUAL_END"


def _patch_between(text: str, start: str, end: str, block: str) -> str:
    pattern = re.compile(
        re.escape(start) + r".*?" + re.escape(end) + r"\n?",
        re.DOTALL,
    )
    if not pattern.search(text):
        raise RuntimeError(f"Markers not found: {start} .. {end}")
    return pattern.sub(block, text, count=1)


def build_sheet_block() -> str:
    if not IMAGE_PATH.is_file():
        raise FileNotFoundError(f"Missing icon sheet: {IMAGE_PATH}")
    raw = IMAGE_PATH.read_bytes()
    b64 = base64.b64encode(raw).decode("ascii")
    kb = len(raw) // 1024
    print(f"Sheet: asak-kiosk-icons-4x4.png (~{kb}KB raw)")
    return (
        f"{SHEET_MARKER_START} — generated by embed_kiosk_icons.py\n"
        f'const KIOSK_ICONS_B64 = "{b64}";  // asak-kiosk-icons-4x4.png · {kb}KB\n'
        f"{SHEET_MARKER_END}\n"
    )


def build_individual_block(icons_dir: Path) -> str:
    lines = [f"{INDIV_MARKER_START} — generated by embed_kiosk_icons.py", "const KIOSK_ICON_B64_BY_SPEC = {"]
    total = 0
    for stem in ICON_NAMES:
        spec = SPEC_NAME_BY_FILE[stem]
        path = icons_dir / f"{stem}.png"
        if not path.is_file():
            raise FileNotFoundError(f"Missing icon PNG: {path}")
        raw = path.read_bytes()
        total += len(raw)
        b64 = base64.b64encode(raw).decode("ascii")
        lines.append(f'  {spec}: "{b64}",  // {stem}.png · {len(raw) // 1024}KB')
    lines.append("};")
    lines.append(INDIV_MARKER_END)
    lines.append("")
    print(f"Individual: {len(ICON_NAMES)} PNGs from {icons_dir} (~{total // 1024}KB raw total)")
    return "\n".join(lines)


def empty_sheet_block() -> str:
    return (
        f"{SHEET_MARKER_START} — generated by embed_kiosk_icons.py\n"
        'const KIOSK_ICONS_B64 = "";  // unused when KIOSK_ICON_B64_BY_SPEC is set\n'
        f"{SHEET_MARKER_END}\n"
    )


def empty_individual_block() -> str:
    return (
        f"{INDIV_MARKER_START} — generated by embed_kiosk_icons.py\n"
        "const KIOSK_ICON_B64_BY_SPEC = {};\n"
        f"{INDIV_MARKER_END}\n"
    )


def patch_code_js(sheet_block: str, indiv_block: str) -> None:
    text = CODE_JS.read_text(encoding="utf-8")
    text = _patch_between(text, SHEET_MARKER_START, SHEET_MARKER_END, sheet_block)
    text = _patch_between(text, INDIV_MARKER_START, INDIV_MARKER_END, indiv_block)
    CODE_JS.write_text(text, encoding="utf-8")
    print(f"Updated {CODE_JS}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--icons-dir",
        type=Path,
        default=ICONS_DIR,
        help="Directory of split PNGs (default: assets/icons)",
    )
    parser.add_argument(
        "--sheet-only",
        action="store_true",
        help="Embed 4x4 sheet only (legacy CROP)",
    )
    args = parser.parse_args()

    use_individual = not args.sheet_only and all(
        (args.icons_dir / f"{stem}.png").is_file() for stem in ICON_NAMES
    )

    if use_individual:
        patch_code_js(empty_sheet_block(), build_individual_block(args.icons_dir))
    else:
        patch_code_js(build_sheet_block(), empty_individual_block())


if __name__ == "__main__":
    main()
