#!/usr/bin/env python3
"""Embed Salady menu PNGs into code.js for offline Figma plugin use.

Source: asak-data/images/menu/{id}.png (from data-pipeline / Salady reference)
Run from repo root or this directory before reloading the plugin in Figma Desktop.
"""
from __future__ import annotations

import base64
import json
import re
from pathlib import Path

PLUGIN_DIR = Path(__file__).resolve().parent
REPO_ROOT = PLUGIN_DIR.parents[2]
CODE_JS = PLUGIN_DIR / "code.js"
IMAGE_ROOT = REPO_ROOT / "asak-data" / "images" / "menu"
MENU_JSON = REPO_ROOT / "asak-data" / "seed" / "menu.json"

# id -> plugin key (keep ≤2 images to limit code.js size)
IMAGE_IDS = {
    "poke_roast_pork": 2534,  # 로스트삼겹 포케볼 — menu photo card + hero
    "salmon_wrap": 4842,  # 그라브락스 연어 랩 — horizontal + sold-out thumb
}

MARKER_START = "// MENU_IMAGES_START — generated by embed_menu_images.py"
MARKER_END = "// MENU_IMAGES_END"


def load_menu_meta() -> dict[int, dict]:
    with MENU_JSON.open(encoding="utf-8") as f:
        rows = json.load(f)
    return {row["id"]: row for row in rows}


def encode_image(menu_id: int) -> tuple[str, int]:
    path = IMAGE_ROOT / f"{menu_id}.png"
    if not path.is_file():
        raise FileNotFoundError(f"Missing menu image: {path}")
    raw = path.read_bytes()
    return base64.b64encode(raw).decode("ascii"), len(raw)


def build_block() -> str:
    meta_by_id = load_menu_meta()
    lines = [
        MARKER_START,
        "const MENU_IMAGES_B64 = {",
    ]
    total_kb = 0
    for key, menu_id in IMAGE_IDS.items():
        b64, size = encode_image(menu_id)
        total_kb += size
        menu = meta_by_id.get(menu_id, {})
        name = menu.get("name", f"id={menu_id}")
        lines.append(f'  {key}: "{b64}",  // menu {menu_id} · {name} · {size // 1024}KB')
    lines.append("};")
    lines.append(MARKER_END)
    print(f"Embedded {len(IMAGE_IDS)} images (~{total_kb // 1024}KB raw → ~{total_kb * 4 // 3 // 1024}KB base64)")
    return "\n".join(lines) + "\n"


def patch_code_js(block: str) -> None:
    text = CODE_JS.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END) + r"\n?",
        re.DOTALL,
    )
    if not pattern.search(text):
        raise RuntimeError(
            f"Markers not found in {CODE_JS.name}. Add {MARKER_START} … {MARKER_END} first."
        )
    CODE_JS.write_text(pattern.sub(block, text, count=1), encoding="utf-8")
    print(f"Updated {CODE_JS}")


def main() -> None:
    block = build_block()
    patch_code_js(block)


if __name__ == "__main__":
    main()
